PRAGMA foreign_keys = ON;
ALTER TABLE user_sessions ADD COLUMN token_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE user_sessions ADD COLUMN absolute_expires_at TEXT;
ALTER TABLE user_sessions ADD COLUMN idle_timeout_seconds INTEGER NOT NULL DEFAULT 2592000;
ALTER TABLE user_sessions ADD COLUMN rotated_at TEXT;
ALTER TABLE user_sessions ADD COLUMN previous_token_hash TEXT;
ALTER TABLE user_sessions ADD COLUMN revoke_reason TEXT;
ALTER TABLE guest_sessions ADD COLUMN token_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE guest_sessions ADD COLUMN absolute_expires_at TEXT;
ALTER TABLE guest_sessions ADD COLUMN idle_timeout_seconds INTEGER NOT NULL DEFAULT 15552000;
ALTER TABLE guest_sessions ADD COLUMN rotated_at TEXT;
ALTER TABLE guest_sessions ADD COLUMN previous_token_hash TEXT;
ALTER TABLE guest_sessions ADD COLUMN revoked_at TEXT;
ALTER TABLE guest_sessions ADD COLUMN revoke_reason TEXT;
ALTER TABLE audit_logs ADD COLUMN prev_hash TEXT;
ALTER TABLE audit_logs ADD COLUMN entry_hash TEXT;
CREATE TABLE IF NOT EXISTS admin_security(user_id TEXT PRIMARY KEY,mfa_required INTEGER NOT NULL DEFAULT 1,mfa_verified_at TEXT,access_enabled INTEGER NOT NULL DEFAULT 0,updated_at TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS csrf_nonces(nonce_hash TEXT PRIMARY KEY,subject_type TEXT NOT NULL,subject_id TEXT NOT NULL,expires_at TEXT NOT NULL,used_at TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS backup_manifests(id TEXT PRIMARY KEY,backup_type TEXT NOT NULL,state TEXT NOT NULL,source_version TEXT,schema_version TEXT,object_count INTEGER,checksum TEXT,created_at TEXT NOT NULL,verified_at TEXT,restore_tested_at TEXT,metadata_json TEXT);
CREATE TABLE IF NOT EXISTS recovery_runs(id TEXT PRIMARY KEY,recovery_type TEXT NOT NULL,state TEXT NOT NULL,started_at TEXT NOT NULL,completed_at TEXT,error_code TEXT,metadata_json TEXT);
