"use strict";
const C=require("./server-contracts.js");
function subjectKey({userId,guestSessionId}){if(userId)return{type:"user",id:String(userId)};if(guestSessionId)return{type:"guest",id:String(guestSessionId)};throw new Error("subject_required")}
function freeAvailable(usedCount,reservedCount,limitCount){const u=Number(usedCount||0),r=Number(reservedCount||0),l=Number(limitCount??3);if(![u,r,l].every(Number.isInteger)||u<0||r<0||l<0)throw new Error("invalid_quota");return Math.max(0,l-u-r)}
function walletAvailable(balance,reservedBalance=0){const b=Number(balance),r=Number(reservedBalance||0);if(![b,r].every(Number.isInteger)||b<0||r<0||r>b)throw new Error("invalid_wallet");return b-r}
function buildFreeQuotaReservation(input={}){const s=subjectKey(input),used=Number(input.usedCount||0),reserved=Number(input.reservedCount||0),limit=Number(input.limitCount??3);if(freeAvailable(used,reserved,limit)<1)throw new Error("free_quota_exhausted");return{mode:"free_quota",subject_type:s.type,subject_id:s.id,quota_key:"ai_chat_free",period_key:String(input.periodKey||"lifetime"),amount:1,used_before:used,used_after:used+1,reserved_before:reserved,reserved_after:reserved+1,limit_count:limit,final_use_on:"AI_SUCCESS_AND_STORED"}}
function buildWalletReservation(input={}){const s=subjectKey(input),amount=C.normalizeCredits(input.amount??1),balance=Number(input.balance),reserved=Number(input.reservedBalance||0),available=walletAvailable(balance,reserved);if(available<amount)throw new Error("insufficient_wallet_balance");return{mode:"wallet",subject_type:s.type,subject_id:s.id,amount,balance_before:balance,balance_after:balance,reserved_before:reserved,reserved_after:reserved+amount,available_before:available,available_after:available-amount,request_id:String(input.requestId||""),idempotency_key:C.requireIdempotencyKey(input.idempotencyKey),final_spend_on:"AI_SUCCESS_AND_STORED"}}
function planAiCharge(input={}){if(Number(input.freeRemaining||0)>0)return{source:"free_quota",amount:1,reserve_required:true,final_charge_on:"AI_SUCCESS_AND_STORED"};const w=Number(input.walletAvailable??input.walletBalance??0);if(w>=1)return{source:"wallet",amount:1,reserve_required:true,final_charge_on:"AI_SUCCESS_AND_STORED"};return{source:"none",amount:0,reserve_required:false,final_charge_on:null,blocked_reason:"no_quota_or_wallet"}}
function shouldReleaseReservation(aiState){return["FAILED_RETRYABLE","FAILED_FINAL","RELEASED"].includes(String(aiState||""))}
function shouldSpendReservation(aiState,durableStored){return String(aiState||"")==="STORED"&&durableStored===true}
function walletAfterSpend({balance,reservedBalance,amount=1}){const b=Number(balance),r=Number(reservedBalance),a=C.normalizeCredits(amount);if(![b,r].every(Number.isInteger)||b<a||r<a)throw new Error("invalid_wallet_spend");return{balance:b-a,reserved_balance:r-a}}
function walletAfterRelease({balance,reservedBalance,amount=1}){const b=Number(balance),r=Number(reservedBalance),a=C.normalizeCredits(amount);if(![b,r].every(Number.isInteger)||r<a||b<0)throw new Error("invalid_wallet_release");return{balance:b,reserved_balance:r-a}}
function quotaAfterSpend({usedCount,reservedCount,amount=1,limitCount=3}){const u=Number(usedCount),r=Number(reservedCount),a=C.normalizeCredits(amount),l=Number(limitCount);if(![u,r,l].every(Number.isInteger)||r<a||u+a>l)throw new Error("invalid_quota_spend");return{used_count:u+a,reserved_count:r-a,limit_count:l}}
function quotaAfterRelease({usedCount,reservedCount,amount=1,limitCount=3}){const u=Number(usedCount),r=Number(reservedCount),a=C.normalizeCredits(amount),l=Number(limitCount);if(![u,r,l].every(Number.isInteger)||r<a)throw new Error("invalid_quota_release");return{used_count:u,reserved_count:r-a,limit_count:l}}
function validateLedgerInvariant({balanceBefore,delta,balanceAfter}){const b=Number(balanceBefore),d=Number(delta),a=Number(balanceAfter);return[b,d,a].every(Number.isInteger)&&a>=0&&b+d===a}
module.exports={subjectKey,freeAvailable,walletAvailable,buildFreeQuotaReservation,buildWalletReservation,planAiCharge,shouldReleaseReservation,shouldSpendReservation,walletAfterSpend,walletAfterRelease,quotaAfterSpend,quotaAfterRelease,validateLedgerInvariant};
